from __future__ import annotations

from typing import Any, Protocol

import numpy as np


class BilevelProblem(Protocol):
    family: str
    dimension: int
    sense: str

    def initial_decision(self) -> np.ndarray: ...
    def response(self, x: np.ndarray, warm: Any | None = None) -> tuple[np.ndarray, Any]: ...
    def objective(self, x: np.ndarray, y: np.ndarray) -> float: ...
    def partial_x(self, x: np.ndarray, y: np.ndarray) -> np.ndarray: ...
    def partial_y(self, x: np.ndarray, y: np.ndarray) -> np.ndarray: ...
    def project(self, x: np.ndarray) -> np.ndarray: ...
